{
  imports = [
    ./adb.nix
    ./audio.nix
    ./bluetooth.nix
    ./desktop.nix
    ./filesystem.nix
    ./firmware.nix
    ./fonts.nix
    ./input.nix
    ./networking.nix
    ./podman.nix
    ./printing.nix
    ./regional.nix
    ./security.nix
    ./shell.nix
    ./udev.nix
  ];
}
