on-unmatched = "info"

[formatter.nixfmt]
command = "nixfmt"
includes = [ "*.nix" ]
priority = 100

[formatter.nixfmt-pretty]
command = "awk"
options = ["-f", "contrib/nixfmt-pretty.awk", "-i", "inplace"]
includes = [ "*.nix" ]
priority = 200

[formatter.black]
command = "uvx"
options = [ "black" ]
includes = [ "*.py" ]
priority = 100

[formatter.ruff]
command = "uvx"
options = [ "ruff", "check", "--fix" ]
includes = [ "*.py" ]
priority = 200

[formatter.shfmt]
command = "shfmt"
options = [ "-w" ]
includes = [ "*.sh" ]
priority = 100

[formatter.stylua]
command = "stylua"
options = [ "--indent-type", "Spaces", "--indent-width", "2" ]
includes = [ "*.lua" ]
priority = 100
