{
  imports = [
    ./blink-cmp.nix
    ./bufferline.nix
    ./comment.nix
    ./committia.nix
    ./copilot.nix
    ./copilot-lualine.nix
    ./csc-nvim.nix
    ./dadbod.nix
    ./flemma-nvim.nix
    ./fugitive.nix
    ./fzf-lua.nix
    ./git-conflict-nvim.nix
    ./gitsigns-nvim.nix
    ./lsp.nix
    ./lspsaga.nix
    ./lualine.nix
    ./markdown-preview-nvim
    ./nvim-autopairs.nix
    ./nvim-hlslens.nix
    ./nvim-tree-lua.nix
    ./quickfix-reflector-vim.nix
    ./repeat.nix
    ./ripgrep.nix
    ./schemastore.nix
    ./sleuth.nix
    ./targets-vim.nix
    ./treesitter.nix
    ./treesitter-context.nix
    ./treesitter-textobjects.nix
    ./ts-autotag.nix
    ./ts-error-translator-nvim.nix
    ./undotree.nix
    ./vim-abolish.nix
    ./vim-asterisk.nix
    ./vim-base64.nix
    ./vim-caser.nix
    ./vim-eunuch.nix
    ./vim-exchange.nix
    ./vim-hexokinase.nix
    ./vim-surround.nix
    ./vim-unimpaired.nix
    ./vim-zend55.nix
    ./web-devicons.nix
    ./yanky.nix
  ];
}
