# Open `nix-diff` in a popup window for path under cursor.
bind-key -T copy-mode-vi d \
    send-keys -X clear-selection \; \
    send-keys -X next-space-end  \; \
    send-keys -X begin-selection \; \
    send-keys -X previous-space  \; \
    send-keys -X copy-pipe-and-cancel "tmux display-popup -EE -xC -yC -w 80% -h 80% -b rounded -s \"bg=#061010\" -S \"bg=#061010,fg=#6f8f8f\" -T \" nix-diff \" \"sh -c 'nix shell nixpkgs#nix-diff --command nix-diff --color=always /run/current-system $( cat <( wl-paste ) ) | ov'\""
